pipeline:
  name: test-alice-vision
  identifier: testalicevision
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: AliceVision
        build: <+input>
  stages:
    - stage:
        name: Build Linux
        identifier: Build_Linux
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Prepare File Tree
                  identifier: Prepare_File_Tree
                  spec:
                    shell: Sh
                    command: |-
                      mkdir ./build
                      mkdir ./build_as_3rdparty
                      mkdir ./functional_tests
                      mkdir ../AV_install
                      git submodule update -i
