pipeline:
  name: test-alice-vision
  identifier: testalicevision
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: prepare file tree
                  identifier: prepare_file_tree
                  spec:
                    shell: Sh
                    command: |-
                      mkdir ./build
                      mkdir ./build_as_3rdparty
                      mkdir ./functional_tests
                      mkdir ../AV_install
                      git submodule update -i
  variables: []
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: alicevision
        build: <+input>
