pipeline:
  name: test-alice-vision
  identifier: testalicevision
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: prepare file tree
                  identifier: prepare_file_tree
                  spec:
                    shell: Sh
                    command: |-
                      mkdir ./build
                      mkdir ./build_as_3rdparty
                      mkdir ./functional_tests
                      mkdir ../AV_install
                      git submodule update -i
              - step:
                  type: Run
                  name: Configure CMake
                  identifier: Configure_CMake
                  spec:
                    shell: Sh
                    command: |-
                      cmake . \
                          -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
                          -DBUILD_SHARED_LIBS:BOOL=ON \
                          -DCMAKE_PREFIX_PATH="${DEPS_INSTALL_DIR}" \
                          -DCMAKE_INSTALL_PREFIX:PATH=$PWD/../../AV_install \
                          -DTARGET_ARCHITECTURE=core \
                          -DALICEVISION_BUILD_TESTS:BOOL=ON \
                          -DALICEVISION_BUILD_EXAMPLES:BOOL=ON \
                          -DALICEVISION_USE_OPENCV:BOOL=ON \
                          -DALICEVISION_USE_CUDA:BOOL=ON \
                          -DALICEVISION_USE_CCTAG:BOOL=ON \
                          -DALICEVISION_USE_POPSIFT:BOOL=ON \
                          -DALICEVISION_USE_ALEMBIC:BOOL=ON  \
                          -DOpenCV_DIR:PATH="${DEPS_INSTALL_DIR}/share/OpenCV" \
                          -DALICEVISION_USE_OPENGV:BOOL=ON \
                          -DOPENGV_DIR:PATH="${DEPS_INSTALL_DIR}" \
                          -DBOOST_NO_CXX11:BOOL=ON \
                          -DCeres_DIR:PATH="${DEPS_INSTALL_DIR}/share/Ceres" \
                          -DEIGEN_INCLUDE_DIR_HINTS:PATH="${DEPS_INSTALL_DIR}" \
                          -DAlembic_DIR:PATH="${DEPS_INSTALL_DIR}/lib/cmake/Alembic"
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    shell: Sh
                    command: make -j$(nproc)
          serviceDependencies:
            - identifier: Container_Deps
              name: Container Deps
              type: Service
              spec:
                connectorRef: account.harnessImage
                image: alicevision/alicevision-deps:ci-2021-04-22-centos7-cuda10.2
          sharedPaths:
            - /build
        variables:
          - name: DEPS_INSTALL_DIR
            type: String
            description: ""
            value: /opt/AliceVision_install
          - name: BUILD_TYPE
            type: String
            description: ""
            value: Release
          - name: CTEST_OUTPUT_ON_FAILURE
            type: Number
            description: ""
            value: 1
  variables: []
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: alicevision
        build: <+input>
